# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepMaxTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RepMaxTools

  pod 'Firebase',  '~> 3.16', :subspecs => [
    'Analytics',
    'Messaging',
  ]  

  target 'RepMaxToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RepMaxTools-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RepMaxTools-tvOS

  target 'RepMaxTools-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
